export const demoData = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    gender: 'Male',
    age: 28,
    profilePicture: 'https://images.unsplash.com/photo-1517841905240-472988babdf9',
    about: 'I love hiking, photography, and traveling the world. Always up for a good adventure!',
    description: 'I’m easy-going, enjoy a good laugh, and appreciate deep conversations.',
    interests: ['Hiking', 'Traveling', 'Photography', 'Cooking'],
    strengths: ['Empathy', 'Adventurous', 'Optimistic', 'Loyal'],
    whatAmILookingFor: {
      relationshipType: 'Serious Relationship',
      personality: ['Adventurous', 'Funny', 'Caring'],
      activities: ['Traveling', 'Dining out', 'Music concerts'],
      qualities: ['Honesty', 'Ambition', 'Sense of humor'],
      communicationStyle: 'Clear and open communication.',
      physicalAttraction: 'Confident and caring individuals.',
    },
    location: {
      city: 'New York',
      country: 'USA',
      latitude: 40.7128,
      longitude: -74.006,
    },
    socialMediaLinks: {
      instagram: 'https://instagram.com/johndoe',
      facebook: 'https://facebook.com/johndoe',
    },
    preferences: {
      ageRange: { min: 25, max: 35 },
      gender: 'Female',
      distance: 50,
    },
    isVerified: true,
    likes: 35,
    dislikes: 3,
    lastOnline: '2025-09-25T15:30:00Z',
    accountStatus: 'Active',
  },
  {
    id: '2',
    firstName: 'Emma',
    lastName: 'Smith',
    gender: 'Female',
    age: 25,
    profilePicture: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    about: 'Music, yoga, and trying new foods. Looking for someone who shares my passion for life.',
    description: 'Creative, energetic, and I believe in living life to the fullest.',
    interests: ['Yoga', 'Music', 'Cooking', 'Traveling'],
    strengths: ['Creative', 'Kind-hearted', 'Optimistic'],
    whatAmILookingFor: {
      relationshipType: 'Casual',
      personality: ['Fun', 'Energetic', 'Open-minded'],
      activities: ['Yoga', 'Music festivals', 'Traveling'],
      qualities: ['Kindness', 'Adventurous', 'Generosity'],
      communicationStyle: 'Honest and open.',
      physicalAttraction: 'Someone who is confident and loves a good laugh.',
    },
    location: {
      city: 'Los Angeles',
      country: 'USA',
      latitude: 34.0522,
      longitude: -118.2437,
    },
    socialMediaLinks: { instagram: 'https://instagram.com/emmasmith' },
    preferences: {
      ageRange: { min: 22, max: 30 },
      gender: 'Male',
      distance: 40,
    },
    isVerified: false,
    likes: 50,
    dislikes: 2,
    lastOnline: '2025-09-24T12:00:00Z',
    accountStatus: 'Active',
  },
  {
    id: '3',
    firstName: 'Liam',
    lastName: 'Williams',
    gender: 'Male',
    age: 30,
    profilePicture: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36',
    about: 'I enjoy sports, especially football, and hanging out with friends.',
    description: 'Outgoing, sports lover, and always looking to try new things.',
    interests: ['Football', 'Movies', 'Traveling'],
    strengths: ['Competitive', 'Optimistic', 'Hard-working'],
    whatAmILookingFor: {
      relationshipType: 'Serious Relationship',
      personality: ['Active', 'Caring', 'Funny'],
      activities: ['Sports', 'Outdoor adventures', 'Traveling'],
      qualities: ['Ambition', 'Sense of humor', 'Loyalty'],
      communicationStyle: 'I appreciate honesty and loyalty.',
      physicalAttraction: 'Someone who is active and enjoys outdoor activities.',
    },
    location: {
      city: 'Chicago',
      country: 'USA',
      latitude: 41.8781,
      longitude: -87.6298,
    },
    socialMediaLinks: { instagram: 'https://instagram.com/liamwilliams' },
    preferences: {
      ageRange: { min: 25, max: 35 },
      gender: 'Female',
      distance: 60,
    },
    isVerified: true,
    likes: 40,
    dislikes: 1,
    lastOnline: '2025-09-24T16:00:00Z',
    accountStatus: 'Active',
  },
  {
    id: '4',
    firstName: 'Olivia',
    lastName: 'Brown',
    gender: 'Female',
    age: 27,
    profilePicture: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
    about: 'A lover of nature, hiking, and good coffee. I’m passionate about sustainability.',
    description: 'Laid-back, loves the outdoors, and values meaningful connections.',
    interests: ['Hiking', 'Photography', 'Sustainability', 'Reading'],
    strengths: ['Empathy', 'Thoughtful', 'Creative'],
    whatAmILookingFor: {
      relationshipType: 'Serious Relationship',
      personality: ['Supportive', 'Kind', 'Adventurous'],
      activities: ['Hiking', 'Art museums', 'Cooking classes'],
      qualities: ['Honesty', 'Kindness', 'Sense of humor'],
      communicationStyle: 'Open and caring.',
      physicalAttraction: 'Someone who shares my passion for nature and sustainability.',
    },
    location: {
      city: 'San Francisco',
      country: 'USA',
      latitude: 37.7749,
      longitude: -122.4194,
    },
    socialMediaLinks: { instagram: 'https://instagram.com/oliviabrown' },
    preferences: {
      ageRange: { min: 25, max: 35 },
      gender: 'Male',
      distance: 50,
    },
    isVerified: false,
    likes: 60,
    dislikes: 0,
    lastOnline: '2025-09-23T18:30:00Z',
    accountStatus: 'Active',
  },
  {
    id: '5',
    firstName: 'Noah',
    lastName: 'Davis',
    gender: 'Male',
    age: 32,
    profilePicture: 'https://images.unsplash.com/photo-1614285964473-3b2b1f3f1c3e',
    about: 'Big fan of tech, gaming, and outdoor adventures.',
    description: 'Tech geek by day, gamer by night. Love to explore new technologies.',
    interests: ['Gaming', 'Tech gadgets', 'Hiking'],
    strengths: ['Analytical', 'Creative', 'Passionate'],
    whatAmILookingFor: {
      relationshipType: 'Casual',
      personality: ['Geeky', 'Funny', 'Creative'],
      activities: ['Tech events', 'Gaming marathons', 'Camping'],
      qualities: ['Intelligence', 'Humor', 'Adventurous'],
      communicationStyle: 'Straightforward and fun.',
      physicalAttraction: 'Someone who enjoys tech and has a good sense of humor.',
    },
    location: {
      city: 'Austin',
      country: 'USA',
      latitude: 30.2672,
      longitude: -97.7431,
    },
    socialMediaLinks: { instagram: 'https://instagram.com/noahdavis' },
    preferences: {
      ageRange: { min: 28, max: 38 },
      gender: 'Female',
      distance: 70,
    },
    isVerified: true,
    likes: 70,
    dislikes: 5,
    lastOnline: '2025-09-22T14:00:00Z',
    accountStatus: 'Active',
  },
];
