export const currentUser = {
  id: '0',
  firstName: 'Hiten',
  lastName: 'Anand',
  email: 'hiten.anand@example.com',
  phone: '+1-555-0100',
  gender: 'Male',
  age: 22,
  dateOfBirth: '2002-06-14',
  profilePicture: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
  additionalPhotos: [
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
    'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
  ],
  about: 'Nature lover 🌿 | Tech enthusiast 💻 | Always curious about new experiences and meaningful connections.',
  description: 'I am an optimistic person who loves meaningful conversations and spending time outdoors. Computer science student with a passion for innovation.',
  interests: ['Hiking', 'Tech', 'Cooking', 'Reading', 'Photography', 'Gaming'],
  strengths: ['Empathy', 'Curiosity', 'Creativity', 'Sense of humor', 'Adaptability'],
  occupation: 'Computer Science Student',
  education: 'Computer Science, Stanford University',
  height: '5ft 10in',
  bodyType: 'Average',
  smokingStatus: 'Non-smoker',
  drinkingStatus: 'Occasionally',
  religion: 'Hindu',
  politicalViews: 'Liberal',
  languages: ['English', 'Hindi', 'Python', 'JavaScript'],
  whatAmILookingFor: {
    relationshipType: 'Serious Relationship',
    personality: ['Caring', 'Adventurous', 'Funny', 'Intelligent'],
    activities: ['Hiking', 'Cooking', 'Traveling', 'Tech meetups'],
    qualities: ['Honesty', 'Kindness', 'Ambition', 'Sense of humor'],
    communicationStyle: 'Honest, direct, and supportive with lots of laughter.',
    physicalAttraction: 'Someone confident, kind, and passionate about life.',
  },
  location: {
    city: 'NYC',
    state: 'NY',
    country: 'USA',
    latitude: 47.6062,
    longitude: -122.3321,
  },
  socialMediaLinks: {
    instagram: 'https://instagram.com/hitenanand',
    facebook: 'https://facebook.com/hitenanand',
    linkedin: 'https://linkedin.com/in/hitenanand',
  },
  preferences: {
    ageRange: { min: 20, max: 28 },
    gender: 'Female',
    distance: 50,
  },
  isVerified: true,
  isEmailVerified: true,
  isPhoneVerified: true,
  profileCompleteness: 98,
  likes: 120,
  dislikes: 4,
  matches: 25,
  views: 445,
  lastOnline: new Date().toISOString(),
  joinedDate: '2024-12-01T10:00:00Z',
  accountStatus: 'Active',
  subscription: 'Premium',
};
